// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoColeta.Data.Contexts;

#nullable disable

namespace ProjetoColeta.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoColeta.Models.ClienteModel", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCliente");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ProjetoColeta.Models.ColetorModel", b =>
                {
                    b.Property<int>("IdColetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColetor"));

                    b.Property<string>("NomeColetor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdColetor");

                    b.ToTable("Coletores", (string)null);
                });

            modelBuilder.Entity("ProjetoColeta.Models.PontoModel", b =>
                {
                    b.Property<int>("IdPonto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPonto"));

                    b.Property<double>("CapacidadeMaxima")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("ColetorModelIdColetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdColetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Status")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdPonto");

                    b.HasIndex("ColetorModelIdColetor");

                    b.HasIndex("IdColetor");

                    b.ToTable("Pontos", (string)null);
                });

            modelBuilder.Entity("ProjetoColeta.Models.ResiduoModel", b =>
                {
                    b.Property<int>("IdResiduo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResiduo"));

                    b.Property<int?>("ClienteModelIdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("EhReciclavel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("Peso")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdResiduo");

                    b.HasIndex("ClienteModelIdCliente");

                    b.HasIndex("IdCliente");

                    b.ToTable("Residuos", (string)null);
                });

            modelBuilder.Entity("ProjetoColetaModels.ColetaModel", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("date");

                    b.Property<int>("IdPonto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdColeta");

                    b.HasIndex("IdPonto");

                    b.ToTable("Coletas", (string)null);
                });

            modelBuilder.Entity("ProjetoColeta.Models.PontoModel", b =>
                {
                    b.HasOne("ProjetoColeta.Models.ColetorModel", null)
                        .WithMany("Pontos")
                        .HasForeignKey("ColetorModelIdColetor");

                    b.HasOne("ProjetoColeta.Models.ColetorModel", "Coletor")
                        .WithMany()
                        .HasForeignKey("IdColetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coletor");
                });

            modelBuilder.Entity("ProjetoColeta.Models.ResiduoModel", b =>
                {
                    b.HasOne("ProjetoColeta.Models.ClienteModel", null)
                        .WithMany("Residuos")
                        .HasForeignKey("ClienteModelIdCliente");

                    b.HasOne("ProjetoColeta.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProjetoColetaModels.ColetaModel", b =>
                {
                    b.HasOne("ProjetoColeta.Models.PontoModel", "Ponto")
                        .WithMany()
                        .HasForeignKey("IdPonto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ponto");
                });

            modelBuilder.Entity("ProjetoColeta.Models.ClienteModel", b =>
                {
                    b.Navigation("Residuos");
                });

            modelBuilder.Entity("ProjetoColeta.Models.ColetorModel", b =>
                {
                    b.Navigation("Pontos");
                });
#pragma warning restore 612, 618
        }
    }
}
