name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar SDK .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar pacotes
        run: dotnet restore ProjetoColeta.sln

      - name: Build do projeto
        run: dotnet build ProjetoColeta.sln --configuration Release --no-restore

      - name: Publicar projeto
        run: dotnet publish ProjetoColeta.sln --configuration Release --output ./publish

      - name: Deploy para o Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "projetocoleta-prd"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRD }}
          package: ./publish
