name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar SDK .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar pacotes
      run: dotnet restore **/ProjetoColeta.sln

    - name: Build do projeto
      run: dotnet build **/ProjetoColeta.sln --configuration Release --no-restore

    - name: Executar testes
      run: dotnet test **/ProjetoColeta.sln --configuration Release --no-build --verbosity normal
